### PR TITLE
EntityPlayerMP null exception

### PR DESCRIPTION
**Pull request by elak93**
With chatgpt help I believe I have addressed an unchecked cast issue in the onPlayerInteract method by adding a type check to ensure safe casting to EntityPlayerMP, mitigating the risk of ClassCastException. To fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16151

### CODE REVIEW

**Comment by Caedis** [comment]
I can already predict a spotless pr by the bot

**Comment by elak93** [comment]
Hmm I did run spotless prior to upload, is there another step to doing that?

**Comment by Caedis** [comment]
Looks like one of the mavens is down. We can try again in a couple hours

**Comment by Dream-Master** [comment]
gradle 8.1.1 was outdated

**Comment by Dream-Master** [comment]
to review this just exlude my addition otherwise its a mess

**Pull request merged**
